
Marcin Magnus

*mmfinder manual*



*usage*
=======================================

Program uzywa updatedb to utworzenia baz danych plikow. Tworzonych jest kilka
baz (bazy zdefiniowane sa w pliku konfiguracyjnym config.py).

'EON'     : '/media/EONVECTOR',
'EON'     : '/media/EONVECTOR',
'SD8GB'   : '/media/SD8GB',
'SD8GB2'   : '/media/8GB2'    ,
'dropbox' : '/home/magnus/Dropbox',

'maximus' : '/home/magnus/',
'1TB'     : '/media/1TB',
'StoreJet'     : '/media/StoreJet',

*OPTIONS*
=======================================

Program umozliwia uruchomienie demona katalogowania. Opcja -u.
#Mozliwe jest takze przeszukiwanie lokalne -l (dropbox + host).
Mozliwe jest takze przeszukiwanie globalne po wszystkich bazach danych, opcja -g (opcja -l local stala sie domyslna)

Niestety dosc trudne okazalo sie odszukanie jedynie folderów. Ostatecznie zdecydowalem 
sie uzyc funkcji find ~ . Minusem tego rozwiazania jest to, ze funkcja 
nie potrafi dzialac zdalnie i jest bardzo, bardzo wolna.

*SYSTEM*
Kolejnym krokiem byloby utworzenie swojego systemu baz danych ktore mialby by informacji
o pliku, jego hash, jego size.

Byc moze uzyc jakies funkcji indekosowania pythonowej
http://stackoverflow.com/questions/532312/python-file-indexing-and-searching

pylucene

*opt obj*

    #print opt {'global_search': False, 'pdf_find': False, 'find_tu': False, 'show_hash': False, 'update_db': False, 'find_dir': False, 'document_find': False, 'find_find': False}
    #print type(opt) <type 'instance'>


*Release Notes*
=======================================
version 0.09
 * -s show hash
 * word, word2
 * -d document odt|doc
 * -u in crontab

version 0.05
 * -p search for pdfs only
 * small changes in if-s

Change of Version 0.04
 * -g global.. opcja przeszukiwania lokalnego staje sie domyslna
 * add StoreJet

[..]


* Ile trwa aktualizowanie baz? (okolo kilku minut)*
real	2m47.866s
user	0m0.980s
sys	0m4.140s

tyle teraz trwa zaktualizowanie baz
***
22 * * * * /home/magnus/Dropbox/workspace/mmfinder/mmfinder.py_deamon.py

* moj db system
lista plikow, info hash, size, czy dyrectory

* INSTALL
  python-pysqlite2
* #TODO#
** TODO 59% problem with apostroph
	'/home/magnus/Downloads/completed/ESL English Advanced Learner's Megapack v6.5/1994 - Murphy, R. - Grammar In Use [Intermediate] - Cambridge - 2nd Edition.PDF'
	file:///home/magnus/Downloads/completed/ESL%20English%20Advanced%20Learner's%20Megapack%20v6.5
	file:///home/magnus/Downloads/completed/ESL%20English%20Advanced%20Learner's%20Megapack%20v6.5/1994%20-%20Murphy,%20R.%20-%20Grammar%20In%20Use%20[Intermediate]%20-%20Cambridge%20-%202nd%20Edition.PDF
	[ -> ??
** DONE wyszukuj z uzyciem 3 slow a nie tylko 2, lub z nieskonczona iloscia tych slow
** TODO wyszukaj jedynie publikacje w konkretnym folderze, poszukaj jakiegos ogolnego rozwiazania np. -f 1 folder f zdefiniowany w pliku config.py
** DONE [-x opcja] w komencie -d exp i wtedy nie wyszukuje tego; np. -r exp aby nie wyszukiwalo jakis plikow itd
** patrz funkcja *check_filetype* sprawdz tam zapisane TODO
** DONE -f opcja dla full search po innych dyskach itd 
** DONE -u opcja dla updatu baz danych przed wykonaniem danego przeszukania
** DONE -s opcja dla wykonania find cmd zamiast locate i danych baz danych, wtedy to zrobic trzeba dla tylko danego dysku
** INFO hash na koncu item, lub size przynajmiej coby wiedziec czy to ten sam plik, no ale wtedy plik nie moze byc z bazy danych
####################################################################################################
['dropbox', 'maximus', 'netbook', 'EON', '8GB2', '1TB']
####################################################################################### dropbox... #
####################################################################################### maximus... #
/home/magnus/.local/share/Trash/info/Unknown - Biochemia - Jeremy M. Berg, Lubert Stryer, John L. Tymoczko.pdf - Unknown - Unknown.pdf.trashinfo
/home/magnus/.local/share/Trash/info/Unknown - Lubert Stryer- Biochemia.pdf - Unknown - Unknown.pdf.trashinfo
/home/magnus/.local/share/Trash/info/Unknown. Biochemia - Jeremy M. Berg, Lubert Stryer, John L. Tymoczko.pdf. Unknown.pdf.trashinfo
/home/magnus/.local/share/Trash/info/Unknown. Lubert Stryer- Biochemia.pdf. Unknown.pdf.trashinfo
/home/magnus/Downloads/completed/Biology/Biochemistry/Berg, Tymoczko, Stryer - Biochemistry - Fifth Edition.pdf
/home/magnus/Downloads/completed/Biology/Biochemistry/Biochemistry 5th ed - Jeremy M. Berg, John L. Tymoczko, Lubert Stryer.pdf
/home/magnus/papers-uam/PDF.LIBRARY/books/books/Books_Szymon/biochemistry.stryer
/home/magnus/papers-uam/PDF.LIBRARY/books/books/Books_Szymon/biochemistry.stryer.rar
/home/magnus/papers-uam/PDF.LIBRARY/books/books/Books_Szymon/biochemistry.stryer/biochemistry.stryer
/home/magnus/papers-uam/uam/PDF.LIBRARY/books/books/Books_Szymon/biochemistry.stryer
/home/magnus/papers-uam/uam/PDF.LIBRARY/books/books/Books_Szymon/biochemistry.stryer/biochemistry.stryer
/home/magnus/pdfbooks/Biochemia - Jeremy M. Berg, Lubert Stryer, John L. Tymoczko.pdf
/home/magnus/pdfbooks/Biochemistry 5th ed - Jeremy M. Berg, John L. Tymoczko, Lubert Stryer WEBversion .pdf
/home/magnus/pdfbooks/Lubert Stryer- Biochemia.pdf @@@@@@@@@@ 423f32 itd HASH @@@@@@@@@@@@@@


** przeszukuj jeszcze jakies inne repozytoria publikacji itd.. inne komputery inne papieru ktorzy maja ludzie





http://127.0.0.1:31945/search?flags=8&hl=en_US&num=20&q=gag&start=0&s=6JDztCZxX2yHbC1AXupw6pgAbw8
adres sie zminia wiec by trzeba bylo to jakos inaczej rozegrac

strona sie przeladowuje itd

by trzeba bylo tampere sprawdzic co sie dzieje.. a potem tez obczaic czy mozna screenscrapping zrobic z pythona .. lub po prostu przekierowanie z konsoli an web



http://127.0.0.1:31945/search?flags=8&hl=en_US&num=20&q=gag&start=0&s=6JDztCZxX2yHbC1AXupw6pgAbw8
adres sie zminia wiec by trzeba bylo to jakos inaczej rozegrac

strona sie przeladowuje itd

by trzeba bylo tampere sprawdzic co sie dzieje.. a potem tez obczaic czy mozna screenscrapping zrobic z pythona .. lub po prostu przekierowanie z konsoli an web

